title: Proteus Helps
email: eduardo.stefanello@schumann.com.br
description: Alguns helps no Protheus
url: "https://stefanelloschumann.github.io"
github_username: stefanelloschumann

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
