title: Stefanello
description: >-
  Alguns helps para as linguagens que eu trabalho

domain: stefanelloschumann.github.io
url: "https://stefanelloschumann.github.io"
twitter_username: dudustefanello
github_username:  stefanelloschumann
email: eduardo@stefanello.cc

timezone: America/Sao_Paulo

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
